Make tests more comprehensive

diff --git a/test b/test
--- a/test
+++ b/test
@@ -8,10 +8,11 @@ docker run --rm "$image" bash -c 'echo util.Properties.versionString | scala' > 
 if [ "$?" -eq 0 ] ; then echo "success"; else echo "failure"; exit 1; fi
 
 echo -n "testing running scala via file... "
-tmp="$(mktemp -d)"
-echo "println(util.Properties.versionString)" > "$tmp/test.scala"
-docker run --rm -v "$tmp:$tmp" "$image" scala "$tmp/test.scala" > /dev/null
-rm -r "$tmp"
+docker run --rm -v "$PWD/testresources:/testresources" "$image" scala "/testresources/testscript.scala" > /dev/null
+if [ "$?" -eq 0 ] ; then echo "success"; else echo "failure"; exit 1; fi
+
+echo -n "testing running scalac... "
+docker run --rm -v "$PWD/testresources:/testresources" "$image" scalac "/testresources/TestClass.scala" > /dev/null
 if [ "$?" -eq 0 ] ; then echo "success"; else echo "failure"; exit 1; fi
 
 echo "all tests passed!"
